USE eztakeout;

CREATE TABLE dish (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(64) NOT NULL COMMENT '菜品名称',
  category_id BIGINT NOT NULL COMMENT '分类ID',
  description VARCHAR(255) COMMENT '菜品描述',
  price DECIMAL(10,2) NOT NULL COMMENT '菜品价格',
  image VARCHAR(255) COMMENT '菜品图片',
  status TINYINT DEFAULT 1 COMMENT '1启售 0停售',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);