USE eztakeout;

CREATE TABLE dish (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(64) NOT NULL COMMENT '菜品名称',
  category_id BIGINT NOT NULL COMMENT '分类ID',
  description VARCHAR(255) COMMENT '菜品描述',
  price DECIMAL(10,2) NOT NULL COMMENT '菜品价格',
  image VARCHAR(255) COMMENT '菜品图片',
  status TINYINT DEFAULT 1 COMMENT '1启售 0停售',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

ALTER TABLE dish ADD COLUMN is_deleted TINYINT DEFAULT 0 COMMENT '是否删除 0否 1是';
ALTER TABLE dish ADD COLUMN sort INT DEFAULT 0 COMMENT '排序号';