CREATE DATABASE eztakeout DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE eztakeout;

CREATE TABLE employee (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(32) NOT NULL UNIQUE COMMENT '用户名',
  password VARCHAR(64) NOT NULL COMMENT '密码',
  name VARCHAR(32) NOT NULL COMMENT '姓名',
  phone VARCHAR(20),
  status TINYINT DEFAULT 1 COMMENT '1启用 0禁用',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE category (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(32) NOT NULL COMMENT '分类名称',
  type INT NOT NULL COMMENT '1菜品分类 2套餐分类',
  sort INT DEFAULT 0 COMMENT '排序号',
  status TINYINT DEFAULT 1 COMMENT '1启用 0禁用',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

